### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by josephernest** [MichalPaszkiewicz/chordprogressiontool#3]
Congratulations for this page that could become a useful tool!
Am I allowed to post a small todo list? ;)
- Remove chord that was added
- Add flat notes (in F key, it's easier to think about Bb major chord instead of A# major chord ;) )
- I don't really see how "Play chords" works... Maybe two buttons : "next chord" / "previous chord" would be easier?
- Saving... We need to be able to save, in order to send by email to friend... Idea: instead of having to deal with a database, server, etc.  we could save in the URL (so that it's easy to "send by email to a friend" a chord progression) : 
  
  `index.html?chord1=AMaj7&chord2=G&chord3=Gm`

**Comment by MichalPaszkiewicz** [comment]
Good ideas, I'll get on it :)

**Comment by MichalPaszkiewicz** [comment]
Fixed!

**Comment by josephernest** [comment]
Waw this is really great!

Just a very small thing: if you go to http://www.michalpaszkiewicz.co.uk/chordprogressiontool/, and add 1 (or 2 or 3) A chords, then the "share link" is not modified.

**Comment by MichalPaszkiewicz** [comment]
Fixed again :dancers: 

Glad you like it :)

Feel free to post more suggestions, if you want.
